package com.web.demo.dto;
// Generated Jun 29, 2021, 8:56:47 AM by Hibernate Tools 5.0.6.Final
/**
 * @author Nguyen Phuong
 */

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;


import org.springframework.web.multipart.MultipartFile;

import com.web.demo.entity.Games;

/**
 * SlideShow generated by hbm2java
 */


public class SlideShowDTO implements java.io.Serializable {

	private Integer idSlideShow;
	private Integer games;
	private MultipartFile  image;

	public SlideShowDTO() {
	}

	public SlideShowDTO(Integer games, MultipartFile  image) {
		this.games = games;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	
	public Integer getIdSlideShow() {
		return this.idSlideShow;
	}

	public void setIdSlideShow(Integer idSlideShow) {
		this.idSlideShow = idSlideShow;
	}

	
	public Integer getGames() {
		return this.games;
	}

	public void setGames(Integer games) {
		this.games = games;
	}

	
	public MultipartFile  getImage() {
		return this.image;
	}

	public void setImage(MultipartFile  image) {
		this.image = image;
	}

}
