package com.web.demo.entity;
// Generated Jul 5, 2021, 11:28:02 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "heroku_0470166a6699307")
public class Category implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_category", unique = true, nullable = false)
	private Integer idCategory;
	@Column(name = "Name_category", length = 45)
	private String nameCategory;
	@ManyToMany(mappedBy = "categories")
	private Set<Games> games = new HashSet<Games>(0);

	public Category() {
	}

	public Category(String nameCategory) {
		this.nameCategory = nameCategory;
		
	}

	
	public Integer getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(Integer idCategory) {
		this.idCategory = idCategory;
	}

	
	public String getNameCategory() {
		return this.nameCategory;
	}

	public void setNameCategory(String nameCategory) {
		this.nameCategory = nameCategory;
	}

	
	public Set<Games> getgames() {
		return this.games;
	}

	public void setgames(Set<Games> games) {
		this.games = games;
	}

}
