package com.web.demo.entity;
// Generated Jul 5, 2021, 11:28:02 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * CommentGame generated by hbm2java
 */
@Entity
@Table(name = "comment_game", catalog = "heroku_0470166a6699307")
public class CommentGame implements java.io.Serializable {


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_comment_game", unique = true, nullable = false)
	private Integer idCommentGame;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_game")
	private Games games;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_users")
	private Users users;
	@Column(name = "Content_comment_game", length = 65535)
	private String contentCommentGame;
	@OneToMany( fetch = FetchType.EAGER, mappedBy = "commentGame")
	private Set<ReplyCommentGame> replyCommentGames = new HashSet<ReplyCommentGame>(0);
	@Temporal(TemporalType.DATE)
	@Column(name = "date")
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date date;
	public CommentGame() {
	}

	public CommentGame(Games games, Users users, String contentCommentGame) {
		this.games = games;
		this.users = users;
		this.contentCommentGame = contentCommentGame;
//		this.replyCommentGames = replyCommentGames;
	}


	public Integer getIdCommentGame() {
		return this.idCommentGame;
	}

	public void setIdCommentGame(Integer idCommentGame) {
		this.idCommentGame = idCommentGame;
	}


	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}


	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	
	public String getContentCommentGame() {
		return this.contentCommentGame;
	}

	public void setContentCommentGame(String contentCommentGame) {
		this.contentCommentGame = contentCommentGame;
	}

	
	public Set<ReplyCommentGame> getReplyCommentGames() {
		return this.replyCommentGames;
	}

	public void setReplyCommentGames(Set<ReplyCommentGame> replyCommentGames) {
		this.replyCommentGames = replyCommentGames;
	}
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
}
