package com.web.demo.entity;
// Generated Jul 5, 2021, 11:28:02 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import org.springframework.format.annotation.DateTimeFormat;

/**
 * Games generated by hbm2java
 */
@Entity
@Table(name = "games", catalog = "megalodondb")
public class Games implements java.io.Serializable {

	
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_game", unique = true, nullable = false)
	private Integer idGame;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_discount")
	private Discount discount;
	@Column(name = "Name_game", nullable = false, length = 45)
	private String nameGame;
	@Column(name = "Producter_game", length = 45)
	private String producterGame;
	@Column(name = "Publisher_game", length = 45)
	private String publisherGame;
	@Temporal(TemporalType.DATE)
	@Column(name = "ReleaseYear_game", length = 10)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date releaseYearGame;
	@Column(name = "Description_game", length = 65535)
	private String descriptionGame;
	@Column(name = "Link_video", length = 100)
	private String linkVideo;
	@Column(name = "Price", precision = 18, scale = 0)
	private Long price;
	@Column(name = "Price_fix", precision = 18, scale = 0)
	private Long priceFix;
	@Column(name = "Rate_game", precision = 12, scale = 0)
	private Float rateGame;
	@Column(name = "Count_sell")
	private Integer countSell;
	@Column(name = "Link_game")
	private String linkGame;
	@Column(name = "count_rate")
	private Integer countRate;
	@Column(name = "Processor", length = 50)
	private String processor;
	@Column(name = "RAM", length = 50)
	private String ram;
	@Column(name = "Free_storage", length = 50)
	private String freeStorage;
	@Column(name = "VGA", length = 50)
	private String vga;
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "games")
	private Set<ImageData> imageDatas = new HashSet<ImageData>(0);
	 @ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
	 @JoinTable(name = "game_category",
			 joinColumns = @JoinColumn(name = "Id_game"),
					 inverseJoinColumns = @JoinColumn(name = "Id_category")
	 )
	private Set<Category> categories = new HashSet<Category>(0);
	 @ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
	 @JoinTable(name = "active_game",
			 joinColumns = @JoinColumn(name = "Id_game"),
					 inverseJoinColumns = @JoinColumn(name = "Id_users")
	 )
	private Set<Users> UsersActive = new HashSet<Users>(0);
//	private Set<CommentGame> commentGames = new HashSet<CommentGame>(0);
//	private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);
//	private Set<SlideShow> slideShows = new HashSet<SlideShow>(0);
	
	
	public Games() {
	}

	public Games(String nameGame) {
		this.nameGame = nameGame;
	}


	public Set<Users> getUsersActive() {
		return UsersActive;
	}

	public void setUsersActive(Set<Users> usersActive) {
		UsersActive = usersActive;
	}

	public Integer getIdGame() {
		return this.idGame;
	}

	public void setIdGame(Integer idGame) {
		this.idGame = idGame;
	}
	

	public Discount getDiscount() {
		return this.discount;
	}

	public void setDiscount(Discount discount) {
		this.discount = discount;
	}

	
	public String getNameGame() {
		return this.nameGame;
	}

	public void setNameGame(String nameGame) {
		this.nameGame = nameGame;
	}

	
	public String getProducterGame() {
		return this.producterGame;
	}

	public void setProducterGame(String producterGame) {
		this.producterGame = producterGame;
	}

	
	public String getPublisherGame() {
		return this.publisherGame;
	}

	public void setPublisherGame(String publisherGame) {
		this.publisherGame = publisherGame;
	}


	public Date getReleaseYearGame() {
		return this.releaseYearGame;
	}

	public void setReleaseYearGame(Date releaseYearGame) {
		this.releaseYearGame = releaseYearGame;
	}


	public String getDescriptionGame() {
		return this.descriptionGame;
	}

	public void setDescriptionGame(String descriptionGame) {
		this.descriptionGame = descriptionGame;
	}

	
	public String getLinkVideo() {
		return this.linkVideo;
	}

	public void setLinkVideo(String linkVideo) {
		this.linkVideo = linkVideo;
	}

	
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	
	public Long getPriceFix() {
		return this.priceFix;
	}

	public void setPriceFix(Long priceFix) {
		this.priceFix = priceFix;
	}

	
	public Float getRateGame() {
		return this.rateGame;
	}

	public void setRateGame(Float rateGame) {
		this.rateGame = rateGame;
	}

	
	public Integer getCountSell() {
		return this.countSell;
	}

	public void setCountSell(Integer countSell) {
		this.countSell = countSell;
	}

	
	public String getLinkGame() {
		return this.linkGame;
	}

	public void setLinkGame(String linkGame) {
		this.linkGame = linkGame;
	}

	
	public Integer getCountRate() {
		return this.countRate;
	}

	public void setCountRate(Integer countRate) {
		this.countRate = countRate;
	}

	
	public String getProcessor() {
		return this.processor;
	}

	public void setProcessor(String processor) {
		this.processor = processor;
	}

	
	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}


	public String getFreeStorage() {
		return this.freeStorage;
	}

	public void setFreeStorage(String freeStorage) {
		this.freeStorage = freeStorage;
	}

	
	public String getVga() {
		return this.vga;
	}

	public void setVga(String vga) {
		this.vga = vga;
	}

	
	public Set<ImageData> getImageDatas() {
		return this.imageDatas;
	}

	public void setImageDatas(Set<ImageData> imageDatas) {
		this.imageDatas = imageDatas;
	}

	
	 
	public Set<Category> getcategories() {
		return this.categories;
	}

	public void setcategories(Set<Category> categories) {
		this.categories = categories;
	}
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "games")
//	public Set<ActiveGame> getActiveGames() {
//		return this.activeGames;
//	}
//
//	public void setActiveGames(Set<ActiveGame> activeGames) {
//		this.activeGames = activeGames;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "games")
//	public Set<CommentGame> getCommentGames() {
//		return this.commentGames;
//	}
//
//	public void setCommentGames(Set<CommentGame> commentGames) {
//		this.commentGames = commentGames;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "games")
//	public Set<BillDetail> getBillDetails() {
//		return this.billDetails;
//	}
//
//	public void setBillDetails(Set<BillDetail> billDetails) {
//		this.billDetails = billDetails;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "games")
//	public Set<SlideShow> getSlideShows() {
//		return this.slideShows;
//	}
//
//	public void setSlideShows(Set<SlideShow> slideShows) {
//		this.slideShows = slideShows;
//	}

}
