package com.web.demo.entity;
// Generated Jul 5, 2021, 11:28:02 AM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImageData generated by hbm2java
 */
@Entity
@Table(name = "image_data", catalog = "megalodondb")
public class ImageData implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_image", unique = true, nullable = false)
	private Integer idImage;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_game", nullable = false)
	private Games games;
	@Column(name = "Name_image", length = 45)
	private String nameImage;

	public ImageData() {
	}

	public ImageData(Games games) {
		this.games = games;
	}

	public ImageData(Games games, String nameImage) {
		this.games = games;
		this.nameImage = nameImage;
	}


	public Integer getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Integer idImage) {
		this.idImage = idImage;
	}
	
	public Games getGames() {
		return this.games;
	}

	public void setGames(Games games) {
		this.games = games;
	}


	public String getNameImage() {
		return this.nameImage;
	}

	public void setNameImage(String nameImage) {
		this.nameImage = nameImage;
	}

}
