package com.web.demo.entity;
// Generated Jul 5, 2021, 11:28:02 AM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemId generated by hbm2java
 */
@Entity
@Table(name = "systems", catalog = "heroku_0470166a6699307")
public class Systems implements java.io.Serializable {


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	private int id;
	@Column(name = "Dowload_system", nullable = false)
	private int dowloadSystem;
	@Column(name = "views_system", nullable = false)
	private int viewsSystem;
	@Column(name = "Date", nullable = false, length = 19)
	
	private Date date;

	public Systems() {
	}

	

	
	public int getDowloadSystem() {
		return this.dowloadSystem;
	}

	public void setDowloadSystem(int dowloadSystem) {
		this.dowloadSystem = dowloadSystem;
	}

	
	public int getViewsSystem() {
		return this.viewsSystem;
	}

	public void setViewsSystem(int viewsSystem) {
		this.viewsSystem = viewsSystem;
	}

	
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getId() {
		return id;
	}



	public void setId(int id) {
		this.id = id;
	}


}
