package com.web.demo.entity;
// Generated Jul 5, 2021, 11:28:02 AM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "megalodondb")
public class Users implements java.io.Serializable {
	

	public Set<Games> getGamesActive() {
		return GamesActive;
	}

	public void setGamesActive(Set<Games> gamesActive) {
		GamesActive = gamesActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id_users", unique = true, nullable = false)
	private Integer idUsers;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Id_role", nullable = false)
	private Role role;
	@Column(name = "Name_users", length = 45)
	private String nameUsers;
	@Column(name = "Username_users", nullable = false, length = 45)
	private String usernameUsers;
	@Column(name = "Password_users", nullable = false, length = 100)
	private String passwordUsers;
	@Column(name = "Email_users", nullable = false, length = 45)
	private String emailUsers;
	@Column(name = "Phone_users", length = 45)
	private String phoneUsers;
	@Column(name = "Image_users", length = 45)
	private String imageUsers;
	@Column(name = "Address_users", length = 45)
	private String addressUsers;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Column(name = "Date_of_birthday", length = 10)
	private Date dateOfBirthday;
	@Column(name = "Gender")
	private Integer gender;
	@Column(name = "Status")
	private Integer status;
	@ManyToMany(mappedBy = "UsersActive")
	private Set<Games> GamesActive = new HashSet<Games>(0);
//	private Set<TokenUser> tokenUsers = new HashSet<TokenUser>(0);
//	private Set<Bill> bills = new HashSet<Bill>(0);
//	private Set<Blog> blogs = new HashSet<Blog>(0);
//	private Set<CommentBlog> commentBlogs = new HashSet<CommentBlog>(0);
//	private Set<CommentGame> commentGames = new HashSet<CommentGame>(0);


	public Users() {
	}

	public Users(Role role, String usernameUsers, String passwordUsers, String emailUsers) {
		this.role = role;
		this.usernameUsers = usernameUsers;
		this.passwordUsers = passwordUsers;
		this.emailUsers = emailUsers;
	}

	public Users(Role role, String nameUsers, String usernameUsers, String passwordUsers, String emailUsers,
			String phoneUsers, String imageUsers, String addressUsers, Date dateOfBirthday, Integer gender,
			Integer status) {
		this.role = role;
		this.nameUsers = nameUsers;
		this.usernameUsers = usernameUsers;
		this.passwordUsers = passwordUsers;
		this.emailUsers = emailUsers;
		this.phoneUsers = phoneUsers;
		this.imageUsers = imageUsers;
		this.addressUsers = addressUsers;
		this.dateOfBirthday = dateOfBirthday;
		this.gender = gender;
		this.status = status;
//		this.tokenUsers = tokenUsers;
//		this.bills = bills;
//		this.blogs = blogs;
//		this.commentBlogs = commentBlogs;
//		this.commentGames = commentGames;
//		this.activeGames = activeGames;
	}

	
	public Integer getIdUsers() {
		return this.idUsers;
	}

	public void setIdUsers(Integer idUsers) {
		this.idUsers = idUsers;
	}

	
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	
	public String getNameUsers() {
		return this.nameUsers;
	}

	public void setNameUsers(String nameUsers) {
		this.nameUsers = nameUsers;
	}

	
	public String getUsernameUsers() {
		return this.usernameUsers;
	}

	public void setUsernameUsers(String usernameUsers) {
		this.usernameUsers = usernameUsers;
	}

	
	public String getPasswordUsers() {
		return this.passwordUsers;
	}

	public void setPasswordUsers(String passwordUsers) {
		this.passwordUsers = passwordUsers;
	}


	public String getEmailUsers() {
		return this.emailUsers;
	}

	public void setEmailUsers(String emailUsers) {
		this.emailUsers = emailUsers;
	}

	
	public String getPhoneUsers() {
		return this.phoneUsers;
	}

	public void setPhoneUsers(String phoneUsers) {
		this.phoneUsers = phoneUsers;
	}

	
	public String getImageUsers() {
		return this.imageUsers;
	}

	public void setImageUsers(String imageUsers) {
		this.imageUsers = imageUsers;
	}

	
	public String getAddressUsers() {
		return this.addressUsers;
	}

	public void setAddressUsers(String addressUsers) {
		this.addressUsers = addressUsers;
	}

	
	public Date getDateOfBirthday() {
		return this.dateOfBirthday;
	}

	public void setDateOfBirthday(Date dateOfBirthday) {
		this.dateOfBirthday = dateOfBirthday;
	}

	
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
//	public Set<TokenUser> getTokenUsers() {
//		return this.tokenUsers;
//	}
//
//	public void setTokenUsers(Set<TokenUser> tokenUsers) {
//		this.tokenUsers = tokenUsers;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
//	public Set<Bill> getBills() {
//		return this.bills;
//	}
//
//	public void setBills(Set<Bill> bills) {
//		this.bills = bills;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
//	public Set<Blog> getBlogs() {
//		return this.blogs;
//	}
//
//	public void setBlogs(Set<Blog> blogs) {
//		this.blogs = blogs;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
//	public Set<CommentBlog> getCommentBlogs() {
//		return this.commentBlogs;
//	}
//
//	public void setCommentBlogs(Set<CommentBlog> commentBlogs) {
//		this.commentBlogs = commentBlogs;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
//	public Set<CommentGame> getCommentGames() {
//		return this.commentGames;
//	}
//
//	public void setCommentGames(Set<CommentGame> commentGames) {
//		this.commentGames = commentGames;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
//	public Set<ActiveGame> getActiveGames() {
//		return this.activeGames;
//	}
//
//	public void setActiveGames(Set<ActiveGame> activeGames) {
//		this.activeGames = activeGames;
//	}

}
